
import { Translations } from './types';

export const TEXTS: Record<'en' | 'zh', Translations> = {
  en: {
    title: "SpriteCutter",
    subtitle: "Split your sprite sheets into individual images instantly.",
    uploadTitle: "Click or Drag to Upload",
    uploadDesc: "Supports PNG, JPG, JPEG, WEBP",
    settings: "Configuration",
    rows: "Rows (Vertical)",
    cols: "Columns (Horizontal)",
    format: "Output Format",
    trimSettings: "Trim Edges (px)",
    trimX: "Horizontal",
    trimY: "Vertical",
    slicePreview: "Preview Slices",
    downloadAll: "Download All as ZIP",
    reset: "Reset",
    processing: "Processing...",
    noImage: "Please upload an image to start",
    generated: "Generated Images",
    width: "Width",
    height: "Height",
    originalSize: "Original Size",
    sliceSize: "Slice Size",
    heroTitle: "Smart Image Sprite Cutter",
    heroSubtitle: "The easiest way to split sprite sheets and multi-action images into separate files.",
    howToUse: "How to Use",
    step1: "Upload your image (Drag & Drop supported)",
    step2: "Set rows and columns to slice",
    step3: "Adjust trim settings to remove grid lines",
    step4: "Preview and download ZIP",
    gotIt: "Got it, let's start!",
  },
  zh: {
    title: "图片切分工具",
    subtitle: "快速将拼图或多动作表情包切分为独立图片。",
    uploadTitle: "点击或拖拽上传图片",
    uploadDesc: "支持 PNG, JPG, JPEG, WEBP",
    settings: "设置",
    rows: "行数 (纵向)",
    cols: "列数 (横向)",
    format: "输出格式",
    trimSettings: "边缘裁切 (px)",
    trimX: "水平",
    trimY: "垂直",
    slicePreview: "切片预览",
    downloadAll: "一键下载 ZIP",
    reset: "重置",
    processing: "处理中...",
    noImage: "请先上传图片",
    generated: "生成的图片",
    width: "宽度",
    height: "高度",
    originalSize: "原始尺寸",
    sliceSize: "切片尺寸",
    heroTitle: "智能图片切分工具",
    heroSubtitle: "一键将拼图、多动作表情包无损切分为独立图片，支持自定义网格与批量下载。",
    howToUse: "使用说明",
    step1: "上传您的图片（支持拖拽）",
    step2: "选择或输入行数和列数",
    step3: "调整边缘裁切以去除不需要的分割线",
    step4: "实时预览并一键下载压缩包",
    gotIt: "明白了，开始使用！",
  }
};
